blog/urls.py
from django.urls import path, re_path
from django.contrib.sitemaps.views import sitemap
from . sitemaps import BlogSitemap
from . import views
from . feeds import RssSiteNewsFeed, AtomSiteNewsFeed
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

sitemaps = {
    'post': BlogSitemap,
    }


app_name = 'blog'
urlpatterns = [
    path('',                     views.IndexView.as_view(), name='index'),
    path('page/<slug:url>/',     views.PageView.as_view(), name='page'),
    path('category/<slug:url>/', views.CategoryView.as_view(), name='category'),
    path('post/<slug:url>/',     views.PostView.as_view(), name='post'),
    path('add-comment/', views.AddCommentPostView.as_view(), name='add_comment'),
    path('sitemap/', views.SitemapView.as_view(), name='sitemap'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('contact/', views.ContactView.as_view(), name='contact'),    
    path('replace-captcha/', views.ReplaceCaptchaAjaxView.as_view(), name='replace_captcha'),  
] 

#redirect
urlpatterns += [
    path('view_post.php', views.RedirectPhpPostView.as_view(), name='view_post'),    
    path('view_cat.php', views.RedirectPhpCategoryView.as_view(), name='view_category'),  
    path('redirect/<slug:title>/', views.RedirectView.as_view(), name='redirect'),    
    re_path('django.wsgi', views.RedirectWsgiView.as_view(), name='redirect_wsgi'),        
]

#ajax
urlpatterns += [
    path('rating-post-ajax/', views.RatingPostView.as_view(), name='rating_post_ajax'),
    path('vote-category-ajax/', views.VoteCategoryAjaxView.as_view(), name='vote_category_ajax'),
    path('online-user-ajax/', views.OnlineUserView.as_view(), name='online_user_ajax'),
]

#xml страницы
urlpatterns += [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('sitenews/rss/', RssSiteNewsFeed()),
    path('sitenews/atom/', AtomSiteNewsFeed()),
]


if settings.DEBUG is True:   #if DEBUG is True it will be served automatically
    #отображение статических картинок + файлы медиа
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

egorch/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    #path('', views.index, name='index'),
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

#капча
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect, QueryDict
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic import CreateView
from django.views.generic.edit import FormView
from django.views.generic import View
from django.views.generic.base import RedirectView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.contrib import messages
from django.urls import reverse_lazy
from .form import *
from django.core.serializers import serialize
import math
import json
from datetime import datetime as dt, timedelta
from django.utils import timezone

from captcha.models import CaptchaStore
from captcha.helpers import captcha_image_url

from .models import *
"""
class QuestionView(generic.DetailView):
    model = Question
    template_name = 'blog/index.html'

class IndexView(generic.DetailView):
    model = PageMenu
    template_name = 'blog/index.html'
    
    '''
    def get(self, request, *args, **kwargs):
        return HttpResponse('Hello, World!')
    
    '''
    def get_queryset(self):        
        return PageMenu.objects.filter(url='index')
        #return self.get()
        
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def index(request):
    index_list = Page.objects.filter(url='index')[0]
    context = {'index_list': index_list}
    print(context)
    return render(request, 'blog/index.html', context)
    
def page(request, url):
    #index_list = Page.objects.filter(url=url)[0]
    '''
    get_object_or_404 - проверяет есть ли такая запись,
    если нет, то переходим на старницу 404
    
    render - соединяет шаблон и контекст(словарь)
    '''
    index_list = get_object_or_404(Page, url=url)
    context = {'index_list': index_list}
    print(context)
    return render(request, 'blog/index.html', context)
    
def category(request, url):
    print(url)
    category_id = get_object_or_404(Category, url=url)
    post_list = Post.objects.filter(category_id=category_id).order_by('title')
    context = {'post_list': post_list}
    return render(request, 'blog/category.html', context)
    
def category_all(request):
    category_list = Category.objects.order_by('title')
    context = {'category_list': category_list}
    print(context)
    return render(request, 'blog/category_all.html', context)   
    
def post(request, url): 
    post_list = get_object_or_404(Post, url=url)
    context = {'post_list': post_list}
    print(post_list)
    return render(request, 'blog/post.html', context)     
"""

class MenuMixin:
    #блок названия категрий
    def get_context_data(self, **kwargs):
        #расширяет функцию
        context = super().get_context_data(**kwargs)
        context['menu_mixin'] = Page.objects.exclude(url='index').exclude(url='contact').exclude(url='sitemap').order_by('position')
        return context

class CategoryMixin:
    #блок названия категрий
    def get_context_data(self, **kwargs):
        #расширяет функцию
        context = super().get_context_data(**kwargs)
        context['category_mixin'] = Category.objects.order_by('title')
        return context
    
class PostTopMixin:
    #блок названия категрий
    def get_context_data(self, **kwargs):
        #расширяет функцию
        context = super().get_context_data(**kwargs)
        context['post_top_mixin'] = Post.objects.filter(visible=True).order_by('-create_date')[:5]
        return context   

class RatingMixin:
    #блок названия категрий
    def get_context_data(self, **kwargs):
        #расширяет функцию
        context = super().get_context_data(**kwargs)
        context['rating_mixin'] = Category.objects.order_by('title')
        return context


class FooterMixin:
    #блок фуутер
    def get_context_data(self, **kwargs):
        #index_list = Page.objects.filter(url='index')[0]
        #index_list = {'text': index_list }
        context = super().get_context_data(**kwargs)
        #данные для футера
        footer = {}
        #можно использовать datetime.datetime.today() встроенный по умолчанию
        footer['year_create'] = dt.today()
        #отображаю только видимые статьи
        footer['count_article'] = Post.objects.filter(visible=True).count()
        footer['comment_article'] = CommentPost.objects.count()
        footer['online_user'] = OnlineUser.objects.count() 
        context['footer_mixin'] = footer
        return context 
    
class SitesFriendsMixin:
    #сайты друзей
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)        
        context['sites_friends_mixin'] = SitesFriends.objects.filter(visible=True)
        return context     

class IndexView(MenuMixin, CategoryMixin, PostTopMixin, RatingMixin, FooterMixin, SitesFriendsMixin, TemplateView):
    model = Page
    template_name = 'blog/page.html'
    context_object_name = 'index_list'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data = self.model.objects.filter(url='index')[0]
        view_page = data.view_page + 1
        #обновление просмотров
        self.model.objects.filter(id=data.id).update(view_page=view_page)
        context['index_list'] = data
        return context

class PageView(MenuMixin, CategoryMixin, PostTopMixin, RatingMixin, FooterMixin, SitesFriendsMixin, DetailView):
    model = Page
    template_name = 'blog/page.html'
    context_object_name = 'index_list'
    slug_field = 'url'
    slug_url_kwarg = 'url'
    
    def get_queryset(self):
        #расширяет функцию
        qs = super().get_queryset()
        url = self.kwargs['url']             
        data = self.model.objects.filter(url=url)[0]
        view_page = data.view_page + 1
        self.model.objects.filter(id=data.id).update(view_page=view_page)
        return qs

    def get_context_data(self, **kwargs):
        #расширяет функцию
        context = super().get_context_data(**kwargs)
        #url = self.kwargs['url']        
        return context


class CategoryView(MenuMixin, CategoryMixin, PostTopMixin, RatingMixin, FooterMixin, SitesFriendsMixin, ListView):
    model = Post
    template_name = 'blog/category.html'
    context_object_name = 'page_list'
    #slug_field = 'url'
    paginate_by = 5
    
    def get_queryset(self):
        #расширяет функцию
        qs = super().get_queryset()
        url = self.kwargs['url']
        self.category = Category.objects.filter(url=url)[0]
        qs = qs.filter(visible=True, category_id=self.category.id).order_by('create_date')
        #qs = qs.filter(visible=True, category_id=self.category.id).order_by('id')
        return qs

    def get_context_data(self, **kwargs):
        #расширяет функцию
        context = super().get_context_data(**kwargs)
        context['category_list'] = self.category
        return context


class PostView(MenuMixin, CategoryMixin, PostTopMixin, RatingMixin, FooterMixin, SitesFriendsMixin, DetailView):
    model = Post
    template_name = 'blog/post.html'
    context_object_name = 'post_list'
    slug_field = 'url'
    slug_url_kwarg = 'url'
    
    def get_queryset(self):
        #расширяет функцию
        qs = super().get_queryset()
        
        return qs

    def get_context_data(self, **kwargs):
        #расширяет функцию
        context = super().get_context_data(**kwargs)
        url = self.kwargs['url']
        
        #отображаю только видимые статьи
        data = self.model.objects.filter(url=url, visible=True)[0]
        view_page = data.view_page + 1
        self.model.objects.filter(id=data.id).update(view_page=view_page)
        
        #для хлебных крошек
        context['category_list'] = Category.objects.filter(id=data.category_id)[0]
                
        #комментарии к статье
        context['comment_list'] = CommentPost.objects.filter(post=data.id).order_by('create_date') 
        
        #форма добавления комментария
        url_full = 'http://' + self.request.META['HTTP_HOST'] + self.request.path

        #context['form'] = CommentPostForm(initial={'url': url_full, 'ip': self.request.META['REMOTE_ADDR']})      
        context['form'] = CommentPostForm(initial={'post': data.id})      
        return context

    
class AddCommentPostView(MenuMixin, CategoryMixin, PostTopMixin, RatingMixin, FooterMixin, SitesFriendsMixin, CreateView):
    model = CommentPost
    form_class = CommentPostForm
    template_name = 'blog/add_comment.html'
    #success_url = reverse_lazy('blog:post', kwargs={'url': '19'})  
    success_url = reverse_lazy('blog:add_comment')  
    
    def form_invalid(self, form):
        response = super().form_invalid(form)        
        messages.error(self.request, 'Ошибка! Комментарий не добавлен!')
        return response
    
    def form_valid(self, form):
        response = super().form_valid(form)   
        #отправка сообщения
        host = self.request.META['REMOTE_ADDR']
        if host != '127.0.0.1':
            data = self.request.POST
            send = send_mail(
                'egorch.ru: комментарий к статье ',
                'страница: ' + self.request.META['HTTP_REFERER'] + ', от ' + data['name_user'] + ', текст: \n' + data['text'],
                'egorchles@yandex.ru',
                ['egorchles@yandex.ru'],
                fail_silently=False,
            )           
            if send == True:
                messages.success(self.request, 'Комментарий успешно добавлен и отослан )')
        else:
            messages.error(self.request, 'Комментарий успешно добавлен, но не отослан')
        return response
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)                
        context['ref'] = self.request.META['HTTP_REFERER'] 

blog/templates/blog/add_comment.html
{% extends "blog/base.html" %}

{% block description %}{{ post_list.description }}{% endblock %}


{% block keywords %}{{ post_list.keywords }}{% endblock %}


{% block title %}{{ post_list.title }}{% endblock %}


{% block content %}
<h1>Добавление комментария</h1>
<div class='message'>
{% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
{% endfor %}

<p><span class="oi oi-arrow-thick-left"></span> перейти на предыдущюю страницу <a href="{{ ref }}">{{ ref }}</a></p>
</div>
{% endblock %}

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Необходимые Мета-теги всегда на первом месте -->  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="{% block description %}{% endblock%}" />
    <meta name="keywords" content="{% block keywords %}{% endblock%}" />
    <title>{% block title %}{% endblock%}</title>

    <!-- Bootstrap -->
    <link href="{% static "bootstrap4/css/bootstrap-grid.min.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap4/css/bootstrap-reboot.min.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap4/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "/open-iconic/font/css/open-iconic-bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "css/styles.css" %}" rel="stylesheet">
	<link rel="shortcut icon" href="{% static "img/favicon.ico" %}" type="image/x-icon">
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static "js/jquery.min.js" %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "bootstrap4/js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "bootstrap4/js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/work.js" %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
     <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="/">egorch.ru</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          {% for page in menu_mixin %}
		    <li>
			  <a class="nav-link" href="{% url 'blog:page' page.url %}">{{ page.title|capfirst }}</a>	  
			</li>
		  {% endfor %}
          <li class="nav-item active">
            <a class="nav-link" href="/contact/">Контакты</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/sitemap/">Карта сайта</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/sitenews/rss/">RSS <span class="oi oi-rss"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/sitenews/atom/">Atom <span class="oi oi-rss"></span></a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'blog:search' %}">
          {% csrf_token %}
          <input name='search' class="form-control mr-sm-2" type="text" placeholder="поиск" aria-label="Search">
          <button class="btn btn btn-secondary my-2 my-sm-0" type="submit">поиск</button>
        </form>
      </div>
    </nav>

    <div class="container-fluid">

	
	<div class="row">
		<div class="col-md-2">
			
			<div class="sidebar-module sidebar-border">
				<p class="h5 center">Категории <span class="oi oi-briefcase"></span></p>
				<ul>
				{% for category in category_mixin %}
				    <li><a href="{% url 'blog:category' category.url %}">{{ category.title|capfirst }}</a></li>
				{% endfor %}
				</ul>
			</div>
			
			<div class="sidebar-module sidebar-border">
				<p class="h5 center">Последние статьи <span class="oi oi-document"></span></p>
				<ul class="last_post">
				{% for post in post_top_mixin %}
				    <li><a href="{% url 'blog:post' post.url %}">{{ post.title }}</a></li>
				{% endfor %}
				</ul>
			</div>
			
			<div class="sidebar-module sidebar-border">
				<span class="d-inline-block vote-help" tabindex="0" data-toggle="tooltip" title="Щелкните по звёздочке )">
					<p class="h5 center">Голосование <span class="oi oi-pie-chart"></span></p>
				</span>
				<table class="table vote">
				{% for cat in rating_mixin %}
					<tr>
				    <td title="{{ cat.title }}">{{ cat.title|capfirst }}</td><td id="button-vote" data-value="{{ cat.url }}"><span class="oi oi-star"></span></td>
				    </tr>
				{% endfor %}
				</table>
			</div>
			<div class="sidebar-module sidebar-border">				
				<noindex>
				<div class="counter-yandex">
					<!-- Yandex.Metrika informer -->
					<a href="https://metrika.yandex.ru/stat/?id=560687&amp;from=informer"
					target="_blank" rel="nofollow"><img src="https://informer.yandex.ru/informer/560687/3_0_FFD386FF_FFB366FF_0_pageviews"
					style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" class="ym-advanced-informer" data-cid="560687" data-lang="ru" /></a>
					<!-- /Yandex.Metrika informer -->
				</div>
								
				<!-- Yandex.Metrika counter -->
				<script type="text/javascript" >
				    (function (d, w, c) {
				        (w[c] = w[c] || []).push(function() {
				            try {
				                w.yaCounter560687 = new Ya.Metrika({
				                    id:560687,
				                    clickmap:true,
				                    trackLinks:true,
				                    accurateTrackBounce:true,
				                    webvisor:true
				                });
				            } catch(e) { }
				        });
				
				        var n = d.getElementsByTagName("script")[0],
				            s = d.createElement("script"),
				            f = function () { n.parentNode.insertBefore(s, n); };
				        s.type = "text/javascript";
				        s.async = true;
				        s.src = "https://mc.yandex.ru/metrika/watch.js";
				
				        if (w.opera == "[object Opera]") {
				            d.addEventListener("DOMContentLoaded", f, false);
				        } else { f(); }
				    })(document, window, "yandex_metrika_callbacks");
				</script>
				<noscript><div><img src="https://mc.yandex.ru/watch/560687" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
				<!-- /Yandex.Metrika counter -->
				</noindex>	
			</div>
		</div>
		<div class="col-md-8">
			<article>
				{% block content %}{% endblock%} 				
			</article>
		</div>
		<div class="col-md-2">
			<div class="sidebar-module sidebar-border">
				<p class="h5 center">Сайты друзей <span class="oi oi-browser"></span></p>
				<ul>
				{% for site in sites_friends_mixin %}
				    <li><a href="{{ site.url }}" title="{{ site.title }}" target=_blank"">{{ site.text }}</a></li>
				{% endfor %}
				</ul>
			</div>
			<!--
			<div class="sidebar-module sidebar-border">
				<p class="h5 center">Реклама <span class="oi oi-bullhorn"></span></p>
				некий текст рекламы от гуугл.				
			</div>
			-->
		</div>
	</div><!--row-->
	
	
	<div class="row">
		<div class="col-md-12">
				<footer>
					<div class="col-md-7 left-box-foot">
						
					{% block footer %}
					<p>
					<a href="/">Видеоуроки уроки CorelDRAW Total Commander для начинающих пользователей чайников</a><br>					
					© 2010 - {{ footer_mixin.year_create|date:"Y" }} Егор Астапов | cайт мониторится с помощью сервиса <a href="http://ping-admin.ru">ping-admin</a>
					</p>
					{% endblock %}
					   
					</div>
					<div class="col-md-5 right-box-foot">
						<p>
						количество статей: {{ footer_mixin.count_article }} | 
						количество комментариев: {{ footer_mixin.comment_article }}  |  
						онлайн: <span id="online-user-num">{{ footer_mixin.online_user }}</span>
						</p>
					 </div>
				</footer>
		</div>
	</div>	

    </div><!-- /.container -->
  </body>
</html>

blog/templates/blog/category.html
{% extends "blog/base.html" %}
{% load static %}

{% block description %}{{ category_list.description }}{% endblock %}


{% block keywords %}{{ category_list.keywords }}{% endblock %}


{% block title %}{{ category_list.title }}{% endblock %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">главная</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blog:category' category_list.url %}">{{ category_list.title }}</a></li>
  </ol>
</nav>
<h1>{{ category_list.h1_title|capfirst }}</h1>


{% for page in page_list %}
<ul class="list-unstyled">
    <li class="media">
	  <a href="{% url 'blog:post' page.url %}"><img class="d-flex mr-3 img-thumbnail" src="{{ MEDIA_URL }}{{ page.mini_icon }}" alt="{{ page.title }}"></a>
	  <div class="media-body">
	    <h{{ forloop.counter }} class="mt-0"><a href="{% url 'blog:post' page.url %}">{{ page.title|capfirst }}</a></h{{ forloop.counter }}>
	    {{ page.description_full }}<br>
	    просмотры: {{ page.view_page }} &nbsp;&nbsp; Автор: {{ page.author }}  &nbsp;&nbsp; дата: {{ page.create_date }}
	  </div>
	</li>
	<hr>
</ul>	
{% empty %}
нет статей!	
<hr>
{% endfor %}
	


{% if is_paginated %}
<div class="pagination-box">
<nav aria-label="Page navigation example">
  <ul class="pagination black">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">предыдущая</a></li>
        {% endif %}

     
        <li class="page-item"><a class="page-link">cтраница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</a></li>
     

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">следующая</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a></li>
        {% endif %}
  </ul>
</nav>
</div>
{% endif %}

рейтинг: {{ category_list.vote }}%
{% endblock %}

blog/templates/blog/contact.html
{% extends "blog/base.html" %}

{% block description %}{{ page.description }}{% endblock %}


{% block keywords %}{{ page.keywords }}{% endblock %}


{% block title %}{{ page.title }}{% endblock %}


{% block content %}
<h1>{{ page.h1_title|capfirst }}</h1>
{{ page.text|safe }}

<form action="" method="post">
	{% csrf_token %}	
	{{ form.as_p }}
	<p><button class='js-captcha-refresh btn btn-outline-dark'>обновить капчу</button></p>
	<button type="submit" class="btn btn-dark">отправить</button>
</form>

<div class='message'>
{% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
{% endfor %}
</div>

<hr>
просмотры: {{ page.view_page }}
{% endblock %}

blog/templates/blog/page.html
{% extends "blog/base.html" %}

{% block description %}{{ index_list.description }}{% endblock %}


{% block keywords %}{{ index_list.keywords }}{% endblock %}


{% block title %}{{ index_list.title }}{% endblock %}



{% block content %}
<h1>{{ index_list.h1_title }}</h1>
{{ index_list.text|safe }}
<hr>
просмотры: {{ index_list.view_page }}
{% endblock %}

blog/templates/blog/post.html
{% extends "blog/base.html" %}
{% load static %}

{% block description %}{{ post_list.description }}{% endblock %}


{% block keywords %}{{ post_list.keywords }}{% endblock %}


{% block title %}{{ post_list.title }}{% endblock %}


{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">главная</a></li>
    <li class="breadcrumb-item"><a href="{% url 'blog:category' category_list.url %}">{{ category_list.title }}</a></li>
  </ol>
</nav>

<h1>{{ post_list.h1_title|capfirst }}</h1>
{{ post_list.text|safe}}
<hr>
рейтинг: <span id="rating-num-info">{{ post_list.rating_result}}</span> &nbsp;&nbsp; просмотры: {{ post_list.view_page }} &nbsp;&nbsp; автор: {{ post_list.author}} &nbsp;&nbsp; создано: {{ post_list.create_date}}
<hr>
<div id="rating-page" data-id-page="{{ post_list.id }}" data-url="{% static 'img/rating/' %}">
    проголосуйте за эту статью:<br>
    <img  data-rating="1" src="{% static 'img/rating/star_rating2.png' %}">
    <img  data-rating="2" src="{% static 'img/rating/star_rating2.png' %}">
    <img  data-rating="3" src="{% static 'img/rating/star_rating2.png' %}">
    <img  data-rating="4" src="{% static 'img/rating/star_rating2.png' %}">
    <img  data-rating="5" src="{% static 'img/rating/star_rating2.png' %}">
</div>

<div class="alert alert-primary rating-alert" role="alert">
  ваш голос учтён!
</div>
                
<div class="comments-page">	
<p class="h4">Комментарии</p>

{% for comment in comment_list %}
	<p>добавил(а): <b>{{ comment.name_user }}</b>&nbsp;|&nbsp;дата: {{ comment.create_date }}<br>
	{{ comment.text }}</p> 
	<hr>
{% empty %}
нет комментариев!	

{% endfor %}



<form method="post" action="{% url 'blog:add_comment' %}">
	{% csrf_token %}	
	{{ form.as_p }}
	<p><button class='js-captcha-refresh btn btn-outline-dark'>обновить капчу</button></p>
	<button type="submit" class="btn btn-dark">отправить</button>
</form>
</div>
{% endblock %}

blog/templates/blog/search.html
{% extends "blog/base.html" %}

{% block description %}{{ post_list.description }}{% endblock %}


{% block keywords %}{{ post_list.keywords }}{% endblock %}


{% block title %}{{ post_list.title }}{% endblock %}


{% block content %}
<h1>Результаты поиска</h1>
<div class='search'>
<ol>
{% for post in search_list %}
	<li><a href='{% url 'blog:post' post.url %}'>{{ post.title }} :: {{ post.category }}</a></li>	
{% empty %}
	нет статей по такому запросу!	
{% endfor %}
</ol>
</div>
{% endblock %}

blog/templates/blog/sitemap.html
{% extends "blog/base.html" %}

{% block description %}{{ page.description }}{% endblock %}


{% block keywords %}{{ page.keywords }}{% endblock %}


{% block title %}{{ page.title }}{% endblock %}


{% block content %}
<h1>Карта сайта</h1>
{{ page.text|safe }}
<div class='sitemap'>
<ol>
	 <li>
	  <a href="/">Главная</a>	  
	</li>
	<li>
	  <a href="{% url 'blog:contact' %}">Контакты</a>	  
	</li>
{% for page in page_list %}
    <li>
	  <a href="{% url 'blog:page' page.url %}">{{ page.title }}</a>	  
	</li>
{% empty %}
нет статей!	
{% endfor %}
</ol>	

<p>Категории:</p>
<ol>
{% for category in category_list %}
    <li>
	  <a href="{% url 'blog:category' category.url %}">{{ category.title }}</a>	  
	</li>
{% empty %}
нет статей!	
{% endfor %}
</ol>	



<p>Статьи блога:</p>
<ol>

{% regroup post_list by category as category_list %}

<ul>
{% for category in category_list %}
    <li>{{ category.grouper }}
    <ol>
        {% for p in category.list %}
          <li><a href='{% url 'blog:post' p.url %}'>{{ p.title }}</a></li>
        {% endfor %}
    </ol>
    </li>
{% endfor %}
</ul>

</ol>	
</div>
<hr>
просмотры: {{ page.view_page }}
{% endblock %}